server:
  port: 8080
spring:
  datasource:
    name: test
    druid:
      url: jdbc:mysql://47.98.219.27:3306/composition?useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 200
        log4j2:
          enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 1000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
        allow: 127.0.0.1
  redis:
    host: localhost
    password:
    port: 6379
# 邮件发送相关的配置
#  mail:
#    host: smtp.qq.com
#    username: 1016767658@qq.com
#    password: ivhkrc*****kbdcf
#    port: 465
#    default-encoding: utf-8
#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true
#            required: true

# Swagger 待具体配置
# 配置文档 https://github.com/SpringForAll/spring-boot-starter-swagger
swagger:
  enabled: true
  title: 批多多系统API文档
  description:
  version: 1.0.0.RELEASE
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: https://gitee.com/se-g11
  contact:
    name:
    url:
    email:
  base-package: cn.edu.zucc.se2020g11
  base-path: /**
  exclude-path: /error, /ops/**
  ui-config:
    submit-methods: get,post,delete,put
    json-editor: true
    show-request-headers: true
    request-timeout: 5000
# 配置日志系统
logging:
  config: classpath:config/log4j2.yml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.zucc.se2020g11.apiserver.entity
jwt:
  http-header: Authorization
  private-key-length: 16
